modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPL v2.1"

[[mods]]
modId = "advjs"
version = "${file.jarVersion}"
displayName = "AdvancementJS"
logoFile = "logo.png"
credits = "Thanks for this example mod goes to Java"
authors = "Westernat"
description = '''Configure advancements by KubeJS'''

[[dependencies.advjs]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advjs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advjs]]
modId = "kubejs"
mandatory = true
versionRange = "[1802.5.5-build.568,)"